name: update

on: 
  workflow_dispatch:
  schedule:
  - cron: 0 */9 * * *

env:
  TZ: Asia/Shanghai

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run script
      run: |
        python script.py

    - name: Commit and push merged_content.txt
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add "Private Rule.txt"
        git commit -m "Update" || echo "No changes to commit"
        git push
        
    - name: Delete workflow runs
      uses: actions/upload-artifact@v2
      with:
        retain_days: 1
        keep_minimum_runs: 5
